### ISSUE TITLE
Crashing, cannot uninstall on Samsung

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [RikkaApps/WADB#30] opened 2022-06-27 07:50 UTC
I cannot unistall the app because when I try, it crashes. I tried wiping, storage, stopping the app, everything.

**Comment by haruue** [comment] 2022-06-27 07:53
You will always uninstall an app even if the app itself keeps crashing.
Could you please provide a screen record to show what happened when you tried to uninstall WADB?

**Comment by IHateTheProgrammingClass** [comment] 2022-06-27 09:14
It has to do something with the package installer sorry.

**Comment by IHateTheProgrammingClass** [comment] 2022-07-02 20:22
nvm I'm dumb. I can uninstall other apps currently, but not this one. The app does not crash, the package installer does. This essentially prevents me from uninstalling it. https://0x0.st/oQNs.mp4

**Comment by haruue** [comment] 2022-07-03 02:40
It should be some bugs in Samsung package installer or some malfunctioning Xposed modules. 

You can try to uninstall WADB with ADB:
1. Enable ADB in the developer options or WADB.
2. Connect your phone to your PC with a USB cable or `adb connect`. (Since you are a user of WADB, I assumed you have ADB installed on your PC and at least know how to run an ADB command)
3. Run the following command
   ```
   adb uninstall moe.haruue.wadb
   ```


And if you want to take an inspection into this problem, you should capture a stack trace about it (as we cannot since we don't have a Samsung device). You can get it with ADB as well.

1. Enable ADB and connect your phone to your PC as above.
2. If you are a Windows user, find or create an empty folder. And while pressing and holding the "Shift" key on your keyboard, click the Right button on your mouse (if you are using Windows 11, you will need to click the "show more options" on this step). You will then see an option that says "Open command window here" or "Open Powershell window here.", click on it and open the terminal with the current path set to the empty folder.
If you are a Mac user or a Linux user, you should already know how to use your terminal and shell.
4. Run the following command in the terminal prompt from step 3.
   ```
   adb logcat -v threadtime '*:V' > log.txt
   ```
   This command would be stuck.
5. Reproduce the issue (uninstall WADB from your home screen) and wait for the package installer to crash.
6. Once the package installer crashes, you can now stop the `adb logcat` command (by pressing Ctrl+C on your computer keyboard or closing the terminal window). And you will find a file named "log.txt" in the empty directory you created in step 2.
7. Open the log.txt with a text editor (such as Notepad++), and you will find a line with `FATAL EXCEPTION` with the package name of the package installer in the following lines. This should be the "Exception" that caused the crash. If you cannot understand them, you can post the whole stack trace here so we will be able to take a look for you.


Since this should not be a bug of WADB, I am closing this issue now. You can still reply to this issue if you need further help.

**Closed by haruue** 2022-07-03 02:40 UTC
